### ISSUE TITLE
Error handling for missing information in a drive log file

### ISSUE THREAD

**Issue by SeiyaNozaki** [cta-observatory/ctapipe_io_lst#104]
I (luckily) found `drive_log_21_05_15.txt` has multiple rows with missing columns.

```
Sun May 16 12:03:56 2021 1621166634 Az -1.360280037 -1.360350013 -1.360239983 0.002782610012 El 95.03820038 95.03820038 95.03829956 0 RA 219.7881927 Dec 56.38958359
95.03820038 95.03829956 0 RA 219.7881927 Dec 56.38958359
Sun May 16 12:03:58 2021 1621166636 Az -1.360270023 -1.360360026 -1.360209942 0.002585940063 El 95.03820038 95.03820038 95.03829956 0 RA 219.796524 Dec 56.38957214
1621166636 Az -1.360270023 -1.360360026 -1.360209942 0.002585940063 El 95.03820038 95.03820038 95.03829956 0 RA 219.796524 Dec 56.38957214
```

This missing info raised an error while r0_to_dl1 script in lstchain.
I tried to add some error handling for this, but didn't find a good solution with astropy table...

Do you have any good solutions...?

**Comment by morcuended** [comment]
I bring attention to this issue again since it has happened for the first time when standard-processing new data, in particular data from 2021-06-12.

The r0_to_dl1 step, for example:

```
lstchain_data_r0_to_dl1 \
 --input-file=/fefs/aswg/data/real/R0/20210612/LST-1.1.Run05034.0000.fits.fz \
 --output-dir=/fefs/aswg/data/real/running_analysis/20210612/v0.7.3 \
 --pedestal-file=/fefs/aswg/data/real/running_analysis/20210612/v0.7.3/drs4_pedestal.Run05020.0000.fits \
 --calibration-file=/fefs/aswg/data/real/running_analysis/20210612/v0.7.3/calibration.Run05021.0000.hdf5 \
 --time-calibration-file=/fefs/aswg/data/real/running_analysis/20210612/v0.7.3/time_calibration.Run05021.0000.hdf5 \
 --pointing-file=/fefs/aswg/data/real/monitoring/DrivePositioning/drive_log_21_06_12.txt \
 --run-summary-path=/fefs/aswg/data/real/monitoring/RunSummary/RunSummary_20210612.ecsv
```

fails with `InconsistentTableError`, saying that the number of columns in the drive log is not what the script expected:

```
Traceback (most recent call last):
  File "/fefs/aswg/software/virtual_env/anaconda3/envs/osa/lib/python3.7/site-packages/astropy/io/ascii/ui.py", line 517, in _guess
    dat = reader.read(table)
  File "/fefs/aswg/software/virtual_env/anaconda3/envs/osa/lib/python3.7/site-packages/astropy/io/ascii/core.py", line 1300, in read
    raise InconsistentTableError(errmsg)
astropy.io.ascii.core.InconsistentTableError: Number of header columns (20) inconsistent with data columns (7) at data line 34484
Header values: ['col1', 'col2', 'col3', 'col4', 'col5', 'col6', 'col7', 'col8', 'col9', 'col10', 'col11', 'col12', 'col13', 'col14', 'col15', 'col16', 'col17', 'col18', 'col19', 'col20']
Data values: ['95.04029846', '95.04039764', '0.03099700063', 'RA', '175.0547028', 'Dec', '56.41064453']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/fefs/aswg/software/virtual_env/anaconda3/envs/osa/bin/lstchain_data_r0_to_dl1", line 8, in <module>
    sys.exit(main())
  File "/fefs/aswg/software/virtual_env/anaconda3/envs/osa/lib/python3.7/site-packages/lstchain/scripts/lstchain_data_r0_to_dl1.py", line 185, in main
    custom_config=config,
  File "/fefs/aswg/software/virtual_env/anaconda3/envs/osa/lib/python3.7/site-packages/lstchain/reco/r0_to_dl1.py", line 328, in r0_to_dl1
    for i, event in enumerate(source):
  File "/fefs/aswg/software/virtual_env/anaconda3/envs/osa/lib/python3.7/site-packages/ctapipe/io/eventsource.py", line 274, in __iter__
    for event in self._generator():
  File "/fefs/aswg/software/virtual_env/anaconda3/envs/osa/lib/python3.7/site-packages/ctapipe_io_lst/__init__.py", line 349, in _generator
    self.fill_pointing_info(array_event)
  File "/fefs/aswg/software/virtual_env/anaconda3/envs/osa/lib/python3.7/site-packages/ctapipe_io_lst/__init__.py", line 593, in fill_pointing_info
    tel_id, array_event.trigger.time,
  File "/fefs/aswg/software/virtual_env/anaconda3/envs/osa/lib/python3.7/site-packages/ctapipe_io_lst/pointing.py", line 101, in get_pointing_position_altaz
    self._read_drive_report_for_tel(tel_id)
  File "/fefs/aswg/software/virtual_env/anaconda3/envs/osa/lib/python3.7/site-packages/ctapipe_io_lst/pointing.py", line 68, in _read_drive_report_for_tel
    self.drive_report[tel_id] = self._read_drive_report(path)
  File "/fefs/aswg/software/virtual_env/anaconda3/envs/osa/lib/python3.7/site-packages/ctapipe_io_lst/pointing.py", line 57, in _read_drive_report
    'Ra', 'target_ra', 'Dec', 'target_dec',
  File "/fefs/aswg/software/virtual_env/anaconda3/envs/osa/lib/python3.7/site-packages/astropy/table/connect.py", line 61, in __call__
    out = registry.read(cls, *args, **kwargs)
  File "/fefs/aswg/software/virtual_env/anaconda3/envs/osa/lib/python3.7/site-packages/astropy/io/registry.py", line 520, in read
    data = reader(*args, **kwargs)
  File "/fefs/aswg/software/virtual_env/anaconda3/envs/osa/lib/python3.7/site-packages/astropy/io/ascii/connect.py", line 18, in io_read
    return read(filename, **kwargs)
  File "/fefs/aswg/software/virtual_env/anaconda3/envs/osa/lib/python3.7/site-packages/astropy/io/ascii/ui.py", line 340, in read
    dat = _guess(table, new_kwargs, format, fast_reader)
  File "/fefs/aswg/software/virtual_env/anaconda3/envs/osa/lib/python3.7/site-packages/astropy/io/ascii/ui.py", line 549, in _guess
    raise core.InconsistentTableError('\n'.join(lines))
ERROR: Unable to guess table format with the guesses listed below:
Reader:Ecsv data_start: 0 delimiter: ' ' fast_reader: {'enable': True} fill_values: [('', '0')] header_start: None names: ['weekday', 'month', 'day', 'time', 'year', 'unix_time', 'Az', 'azimuth_avg', 'azimuth_min', 'azimuth_max', 'azimuth
_std', 'El', 'zenith_avg', 'zenith_min', 'zenith_max', 'zenith_std', 'Ra', 'target_ra', 'Dec', 'target_dec'] strict_names: True
...

************************************************************************
** ERROR: Unable to guess table format with the guesses listed above. **
**                                                                    **
** To figure out why the table did not read, use guess=False and      **
** fast_reader=False, along with any appropriate arguments to read(). **
** In particular specify the format and any known attributes like the **
** delimiter.                                                         **
************************************************************************
```

Due to this error, the data was not processed yet.

Again there are some rows with missing information, hence astropy cannot interpret the table:
```
Sun Jun 13 12:04:33 2021 1623585870 Az -1.358270049 -1.358319998 -1.358240008 0.002445410006 El 95.04389954 95.04389954 95.04399872 0 RA 247.5809326 Dec 56.33856201
-1.358270049 -1.358319998 -1.358240008 0.002445410006 El 95.04389954 95.04389954 95.04399872 0 RA 247.5809326 Dec 56.33856201
Sun Jun 13 12:04:35 2021 1623585872 Az -1.358260036 -1.358319998 -1.358219981 0.003062739968 El 95.04389954 95.04389954 95.04399872 0 RA 247.5893707 Dec 56.33856583
Sun Jun 13 12:04:35 2021 1623585872 Az -1.358260036 -1.358319998 -1.358219981 0.003062739968 El 95.04389954 95.04389954 95.04399872 0 RA 247.5893707 Dec 56.33856583
Sun Jun 13 12:04:35 2021 1623585872 Az -1.358260036 -1.358319998 -1.358219981 0.003062739968 El 95.04389954 95.04389954 95.04399872 0 RA 247.5893707 Dec 56.33856583
Sun Jun 13 12:04:36 2021 1623585874 Az -1.358279943 -1.358360052 -1.358240008 0.001906540012 El 95.04389954 95.04389954 95.04389954 0 RA 247.6018524 Dec 56.33852386
-1.358279943 -1.358360052 -1.358240008 0.001906540012 El 95.04389954 95.04389954 95.04389954 0 RA 247.6018524 Dec 56.33852386
Sun Jun 13 12:04:38 2021 1623585876 Az -1.358279943 -1.358330011 -1.358219981 0.002297060098 El 95.04389954 95.04380035 95.04389954 0.03099280037 RA 247.6060791 Dec 56.33851242
95.04389954 95.04380035 95.04389954 0.03099280037 RA 247.6060791 Dec 56.33851242                                        
Sun Jun 13 12:04:41 2021 1623585878 Az -1.358289957 -1.358360052 -1.358240008 0.001531369984 El 95.04389954 95.04380035 95.04389954 0 RA 247.6144867 Dec 56.33853531
Sun Jun 13 12:04:41 2021 1623585878 Az -1.358289957 -1.358360052 -1.358240008 0.001531369984 El 95.04389954 95.04380035 95.04389954 0 RA 247.6144867 Dec 56.33853531
Sun Jun 13 12:04:41 2021 1623585878 Az -1.358289957 -1.358360052 -1.358240008 0.001531369984 El 95.04389954 95.04380035 95.04389954 0 RA 247.6144867 Dec 56.33853531
Sun Jun 13 12:04:42 2021 1623585880 Az -1.358279943 -1.358330011 -1.358240008 0.002082299907 El 95.04389954 95.04380035 95.04389954 0 RA 247.6227722 Dec 56.33852386
247.6227722 Dec 56.33852386                                                                                             
Sun Jun 13 12:04:45 2021 1623585882 Az -1.358289957 -1.358389974 -1.358240008 0.001234799973 El 95.04380035 95.04380035 95.04389954 0 RA 247.6354218 Dec 56.3385849
Sun Jun 13 12:04:45 2021 1623585882 Az -1.358289957 -1.358389974 -1.358240008 0.001234799973 El 95.04380035 95.04380035 95.04389954 0 RA 247.6354218 Dec 56.3385849
Sun Jun 13 12:04:46 2021 1623585884 Az -1.358289957 -1.358360052 -1.358240008 0.001677530003 El 95.04380035 95.04370117 95.04389954 0 RA 247.6395569 Dec 56.33857727
Sun Jun 13 12:04:46 2021 1623585884 Az -1.358289957 -1.358360052 -1.358240008 0.001677530003 El 95.04380035 95.04370117 95.04389954 0 RA 247.6395569 Dec 56.33857727
Sun Jun 13 12:04:46 2021 1623585884 Az -1.358289957 -1.358360052 -1.358240008 0.001677530003 El 95.04380035 95.04370117 95.04389954 0 RA 247.6395569 Dec 56.33857727
Sun Jun 13 12:04:48 2021 1623585886 Az -1.358289957 -1.358360052 -1.358250022 0.001569189946 El 95.04380035 95.04370117 95.04380035 0 RA 247.6479797 Dec 56.33856964
Sun Jun 13 12:04:48 2021 1623585886 Az -1.358289957 -1.358360052 -1.358250022 0.001569189946 El 95.04380035 95.04370117 95.04380035 0 RA 247.6479797 Dec 56.33856964
Sun Jun 13 12:04:48 2021 1623585886 Az -1.358289957 -1.358360052 -1.358250022 0.001569189946 El 95.04380035 95.04370117 95.04380035 0 RA 247.6479797 Dec 56.33856964
Sun Jun 13 12:04:51 2021 1623585888 Az -1.358289957 -1.358340025 -1.358250022 0.001027130056 El 95.04380035 95.04370117 95.04380035 0 RA 247.6605377 Dec 56.33853149
Sun Jun 13 12:04:51 2021 1623585888 Az -1.358289957 -1.358340025 -1.358250022 0.001027130056 El 95.04380035 95.04370117 95.04380035 0 RA 247.6605377 Dec 56.33853149
Sun Jun 13 12:04:51 2021 1623585888 Az -1.358289957 -1.358340025 -1.358250022 0.001027130056 El 95.04380035 95.04370117 95.04380035 0 RA 247.6605377 Dec 56.33853149
Sun Jun 13 12:04:51 2021 1623585890 Az -1.358299971 -1.358399987 -1.358250022 0.001412049984 El 95.04370117 95.04370117 95.04380035 0.03099700063 RA 247.6646576 Dec 56.33860779
-1.358299971 -1.358399987 -1.358250022 0.001412049984 El 95.04370117 95.04370117 95.04380035 0.03099700063 RA 247.6646576 Dec 56.33860779
Sun Jun 13 12:04:55 2021 1623585892 Az -1.358309984 -1.358369946 -1.358270049 0.000484262011 El 95.04370117 95.04370117 95.04380035 0 RA 247.6730499 Dec 56.33852386
```

**Comment by maxnoe** [comment]
Can we just skip broken rows? Or is there a larger problem? Why are these drive reports malformated?

There seems to be just random additional data in there.

Interestingly, this addition data seems to be repeated values from the other lines? Or is data missing?

**Comment by maxnoe** [comment]
Most importantly would be to report this to whatever software is writing these reports.

**Comment by maxnoe** [comment]
The broken files were repaired. I think we don't need any other handling here, since we get a clear error for broken files and the issue is elsewhere
