### ISSUE TITLE
Support for data with missing modules in R1v1 / EVBv6 format

### ISSUE THREAD

**Issue by SeiyaNozaki** [cta-observatory/ctapipe_io_lst#214]
I got an error when applying DRS calibration to data with missing module.
```
(lstchain-v0.10.7) [seiya.nozaki@cp03 seiya.nozaki]$ lstchain_create_drs4_pedestal_file -m 25000 -i /fefs/onsite/data/20240310/LST-1.1.Run17016.0000.fits.fz -o temp
0it [00:01, ?it/s]
2024-03-10 22:26:08,849 ERROR [lstchain.lstchain_create_drs4_pedestal_file] (tool.run): Caught unexpected exception: operands could not be broadcast together with shapes (2,1855) (1848,) 
Traceback (most recent call last):
  File "/fefs/aswg/software/conda/envs/lstchain-v0.10.7/lib/python3.11/site-packages/ctapipe/core/tool.py", line 426, in run
    self.start()
  File "/fefs/aswg/software/conda/envs/lstchain-v0.10.7/lib/python3.11/site-packages/lstchain/tools/lstchain_create_drs4_pedestal_file.py", line 217, in start
    for event in tqdm(self.source, disable=not self.progress_bar):
  File "/fefs/aswg/software/conda/envs/lstchain-v0.10.7/lib/python3.11/site-packages/tqdm/std.py", line 1182, in __iter__
    for obj in iterable:
  File "/fefs/aswg/software/conda/envs/lstchain-v0.10.7/lib/python3.11/site-packages/ctapipe/io/eventsource.py", line 323, in __iter__
    for event in self._generator():
  File "/fefs/aswg/software/conda/envs/lstchain-v0.10.7/lib/python3.11/site-packages/ctapipe_io_lst/__init__.py", line 656, in _generator
    self.r0_r1_calibrator.apply_drs4_corrections(array_event)
  File "/fefs/aswg/software/conda/envs/lstchain-v0.10.7/lib/python3.11/site-packages/ctapipe_io_lst/calibration.py", line 263, in apply_drs4_corrections
    invalid_pixels = broken_pixels | dvred_pixels
                     ~~~~~~~~~~~~~~^~~~~~~~~~~~~~
ValueError: operands could not be broadcast together with shapes (2,1855) (1848,) 

```
The corresponding codes are here, implemented in #179
https://github.com/cta-observatory/ctapipe_io_lst/blob/3a4deee5b86279555bf2bfba9cd753751f5dba3d/src/ctapipe_io_lst/calibration.py#L260-L262

Actually the size of those array is different (1855 vs 1847). So we need to fix it, and also the test for data with missing module is not enough.
![image](https://github.com/cta-observatory/ctapipe_io_lst/assets/31307823/b0183282-1196-48f0-b5ac-7c468665c308)

**Comment by moralejo** [comment]
This also has to be fixed to deal with DVR'ed data, so it is linked to #213

**Comment by SeiyaNozaki** [comment]
I'm using the data with the missing module taken March 10 (run 17016).
